import { ArrowUpRight, ArrowRight, CalendarDays, MapPin, Clock3, Flag, Route, Heart, Users } from 'lucide-react';
const live = 'https://mwcorvettes.com';
const events = [
  { day: '15', month: 'SEP', kind: 'SOCIAL', title: 'An evening for ice cream.', name: 'Ice Cream Run · Cherry Flamingo', when: 'Tuesday, September 15 · 6:30 pm', where: 'Port Byron, Illinois', href: '/club-events/ice-cream-run-cherry-flamingo-in-port-byron/' },
  { day: '20', month: 'SEP', kind: 'DRIVE-OUT', title: 'See where the road takes us.', name: 'September Club Drive-Out', when: 'Sunday, September 20', where: 'Destination to be announced', href: '/club-events/drive-out-sept-19th-tbd/' },
  { day: '03', month: 'OCT', kind: 'CAR SHOW', title: 'Great cars. A good cause.', name: 'Denny Waddell Memorial Car Show', when: 'Saturday, October 3 · Registration 8 am', where: 'Eriksen Chevrolet · Milan, Illinois', href: '/club-events/denny-waddell-memorial-all-corvette-car-show/' },
];
export default function Home() {
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <div className="utility"><div className="shell utility-inner"><span>QUAD CITIES, IOWA & ILLINOIS <span className="utility-dot">/</span> EST. 1960</span><a href={live}>Already a member? <span>Visit member site <ArrowUpRight size={13}/></span></a></div></div>
    <header className="header"><div className="shell header-inner"><a href="#" className="brand" aria-label="Mid-West Corvettes home"><img src={`${process.env.NEXT_PUBLIC_BASE_PATH || ''}/images/mwc-logo.png`} alt="Mid-West Corvettes" width="100" height="65"/><span>MID-WEST<br/><strong>CORVETTES</strong></span></a><nav className="desktop-nav" aria-label="Main navigation"><a href="#about">The Club</a><a href="#events">Events</a><a href="#photos">Photos</a><a href={`${live}/contact/`}>Contact</a></nav><a className="button button-dark header-join" href="#membership">Join the club <ArrowUpRight size={17}/></a><details className="mobile-nav"><summary>Menu</summary><nav aria-label="Mobile navigation"><a href="#about">The Club</a><a href="#events">Events</a><a href="#photos">Photos</a><a href="#membership">Membership</a><a href={`${live}/contact/`}>Contact</a></nav></details></div></header>
    <main id="main">
      <section className="hero" aria-labelledby="hero-title"><div className="hero-photo"><img src={`${process.env.NEXT_PUBLIC_BASE_PATH || ''}/images/club-aerial.jpg`} alt="Mid-West Corvettes members gathered between two rows of their colorful Corvettes" width="1600" height="1000" fetchPriority="high"/></div><div className="shell hero-inner"><div className="hero-copy"><p className="eyebrow"><span className="yellow-line"/>CORVETTES. FRIENDS. COMMUNITY.</p><h1 id="hero-title">Great cars.<br/>Even better<br/><em>company.</em></h1><p className="hero-description">Open roads. Shared stories. A love of the Corvette.<br className="desktop-break"/> Find your people in the Quad Cities.</p><div className="hero-actions"><a className="button button-yellow" href="#events">Find your next outing <ArrowRight size={18}/></a><a className="hero-secondary" href="#membership">Get to know the club <ArrowUpRight size={17}/></a></div></div><div className="photo-credit"><span/> OUR CARS. OUR PEOPLE. OUR CLUB.</div></div></section>
      <div className="meeting-strip"><div className="shell meeting-inner"><span className="meeting-icon"><CalendarDays size={23}/></span><div><strong>Come for a meeting. Stay for the friendships.</strong><p>First Tuesday of the month · 6:30 pm · Eriksen Chevrolet, Milan, IL</p></div><a href="#membership">Guests are always welcome <ArrowUpRight size={19}/></a></div></div>
      <section id="events" className="section events-section shell"><div className="section-top"><div><p className="eyebrow muted">MAKE SOME PLANS</p><h2>Good times ahead.</h2></div><a className="text-link" href={`${live}/club-events/`}>View full calendar <ArrowUpRight size={19}/></a></div><div className="event-grid">{events.map(e=><a className="event-card" href={live+e.href} key={e.day+e.month}><div className="event-top"><div className="date-block"><span>{e.month}</span><strong>{e.day}</strong></div><span className="event-kind">{e.kind}</span><ArrowUpRight className="event-arrow" size={22}/></div><h3>{e.title}</h3><p className="event-name">{e.name}</p><div className="event-meta"><p><Clock3 size={15}/>{e.when}</p><p><MapPin size={15}/>{e.where}</p></div></a>)}</div><p className="calendar-note">September–October 2026 highlights. Check the club calendar for the latest details.</p></section>
      <section className="club-section" id="about"><div className="shell club-grid"><div className="club-image"><img src={`${process.env.NEXT_PUBLIC_BASE_PATH || ''}/images/club-anniversary.jpg`} alt="Club members and their Corvettes lined up for the Mid-West Corvettes 50th anniversary" width="1280" height="790" loading="lazy"/><div className="heritage-stamp"><strong>1960</strong><span>THE START OF<br/>SOMETHING GOOD.</span></div></div><div className="club-copy"><p className="eyebrow muted">A SHARED PASSION. A LASTING CONNECTION.</p><h2>The Corvette<br/>is just the beginning.</h2><p>Since 1960, Mid-West Corvettes has brought people together on both sides of the Mississippi. What starts with a shared love of a car grows into road trips, familiar faces, and friendships that last.</p><p>From a Saturday drive-out to a fundraiser for local children, there’s always another reason to get together.</p><a className="text-link" href={`${live}/history/`}>Meet a club with a little history <ArrowUpRight size={19}/></a></div></div></section>
      <section className="section shell activities"><div className="section-top"><div><p className="eyebrow muted">MORE WAYS TO ENJOY THE RIDE</p><h2>Find your kind of fun.</h2></div><p className="section-aside">Pick a favorite. Try something new.<br/>There’s a place for you here.</p></div><div className="activity-grid">{[{Icon:Route,n:'01',title:'Hit the open road',text:'Scenic drive-outs, day trips, and adventures a little farther from home.',href:'/drive-outs/'},{Icon:Flag,n:'02',title:'Share your passion',text:'Car shows, rallies, and autocross with people who get it.',href:'/rallys/'},{Icon:Users,n:'03',title:'Pull up a chair',text:'Breakfasts, picnics, ice cream runs, and good company all year long.',href:'/social/'},{Icon:Heart,n:'04',title:'Give something back',text:'Come together to support local children, families, and our community.',href:'/charity/'}].map(({Icon,n,title,text,href})=><a className="activity" href={live+href} key={n}><div className="activity-top"><Icon size={27} strokeWidth={1.4}/><span>{n}</span></div><h3>{title}</h3><p>{text}</p><ArrowUpRight size={20}/></a>)}</div></section>
      <section className="membership-section" id="membership"><div className="shell membership-grid"><div><p className="eyebrow">THERE’S ROOM FOR ONE MORE.</p><h2>Your Corvette.<br/>Your next chapter.</h2><p>You bring the passion. We’ll introduce you to the people.<br/>Come to a meeting as our guest and see what MWC is all about.</p><a className="button button-yellow" href={`${live}/membership/`}>Explore membership <ArrowUpRight size={18}/></a></div><div className="meeting-card"><span className="eyebrow">YOUR FIRST VISIT</span><h3>Let’s meet in Milan.</h3><p><CalendarDays size={19}/><span>First Tuesday of every month<br/><strong>6:30 pm</strong></span></p><p><MapPin size={19}/><span>Eriksen Chevrolet<br/>325 1st Ave E, Milan, IL 61264</span></p><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=Eriksen+Chevrolet+325+1st+Ave+E+Milan+IL+61264" target="_blank" rel="noreferrer">Get directions <ArrowUpRight size={18}/></a><div className="meeting-footnote">Meet the members, ask questions, and make yourself at home.</div></div></div></section>
      <section id="photos" className="photos-section shell"><div><p className="eyebrow muted">THE MILES. THE MEMORIES.</p><h2>See life with MWC.</h2><p>Take a look at the cars, places, and people that make this club our own.</p></div><a className="button button-outline" href="https://www.flickr.com/photos/145199657@N05/albums" target="_blank" rel="noreferrer">Explore club photo albums <ArrowUpRight size={18}/></a></section>
    </main>
    <footer><div className="shell footer-main"><a href="#" className="footer-brand">MID-WEST CORVETTES<span>Corvettes, friends, community. Since 1960.</span></a><div className="footer-links"><a href={`${live}/contact/`}>Contact the club <ArrowUpRight size={15}/></a><a href={`${live}/corvettes-for-sale/`}>Buy / Sell <ArrowUpRight size={15}/></a><a href="https://www.facebook.com/groups/203644606324869/" target="_blank" rel="noreferrer">Facebook <ArrowUpRight size={15}/></a></div></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} Mid-West Corvettes, Inc. · Quad Cities, IA & IL</span><span className="wave">SAVE THE WAVE. <span aria-hidden="true">✌</span></span></div></footer>
  </>;
}
